export const START_LOADING_MENUS = 'START_LOADING_MENUS';
export const MENUS_FAILED = 'MENUS_FAILED';
export const ADD_MENUS = 'ADD_MENUS';
export const CREATE_MENU = 'CREATE_MENU';
export const DELETE_MENU = 'DELETE_MENU';

export const START_LOADING_DISHES = 'START_LOADING_DISHES';
export const END_LOADING_DISHES = 'END_LOADING_DISHES';
export const DISHES_FAILED = 'DISHES_FAILED';
export const ADD_DISHES = 'ADD_DISHES';
export const CREATE_MEAL = 'CREATE_MEAL';
export const DELETE_MEAL = 'DELETE_MEAL';

export const START_LOADING_PHOTOS = 'START_LOADING_PHOTOS';
export const ADD_PHOTOS = 'ADD_PHOTOS';
export const PHOTOS_FAILED = 'PHOTOS_FAILED';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const START_LOADING_GROCERIES = 'START_LOADING_GROCERIES';
export const ADD_GROCERIES = 'ADD_GROCERIES';
export const GROCERIES_FAILED = 'GROCERIES_FAILED';
