export const START_LOADING_MENUS = 'START_LOADING_MENUS';
export const MENUS_FAILED = 'MENUS_FAILED';
export const ADD_MENUS = 'ADD_MENUS';

export const START_LOADING_DISHES = 'START_LOADING_DISHES';
export const END_LOADING_DISHES = 'END_LOADING_DISHES';
export const DISHES_FAILED = 'DISHES_FAILED';
export const ADD_DISHES = 'ADD_DISHES';

export const START_LOADING_PHOTOS = 'START_LOADING_PHOTOS';
export const ADD_PHOTOS = 'ADD_PHOTOS';
export const PHOTOS_FAILED = 'PHOTOS_FAILED';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';